const PROGRAM = 0;
const NUMBER_LITERAL = 1;
const STRING_LITERAL = 2;
const CALL_EXPRESSION = 3;
const EXPRESSION_STATEMENT = 4;
const IDENTIFIER = 5;

module.exports = {
	PROGRAM,
	NUMBER_LITERAL,
	STRING_LITERAL,
	CALL_EXPRESSION,
	EXPRESSION_STATEMENT,
	IDENTIFIER,
};
